// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d9420771-067d-4673-8338-436fbd1af427",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4QeOKadco",
    "aws_user_pools_web_client_id": "1jhksf1rn70lnpn16jbtp8f1ae",
    "aws_user_files_s3_bucket": "newpicbuck",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
